1:
	gcc -o 1 main1.c
	# gagal
2:
	gcc -o 2 main2.c
	# gagal
3:
	gcc -o 3 main3.c
4:
	gcc -o 4 main4.c
5:
	gcc -o 5 main5.c
6:
	gcc -o 6 main6.c
7:
	gcc -o 7 main7.c
# ket : yang tidak ada keterangan gagal, berarti sukses