M48
; DRILL file {KiCad (7.99.0-200-gad838e3d73)} date Thu Mar  7 11:34:15 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-07T11:34:15+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.99.0-200-gad838e3d73)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X1.67Y-2.61
X1.67Y-3.51
X1.7Y-5.72
X1.83Y-6.73
T0
M30
