M48
; DRILL file {KiCad (7.99.0-200-gad838e3d73)} date Thu Mar  7 11:40:59 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-07T11:40:59+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.99.0-200-gad838e3d73)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X7.46Y-2.75
X7.46Y-4.36
X9.73Y-2.75
X9.73Y-4.36
T0
M30
