M48
; DRILL file {KiCad (7.99.0-200-gad838e3d73)} date Mon Mar 11 18:14:07 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-11T18:14:07+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.99.0-200-gad838e3d73)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
%
G90
G05
T1
X2.702Y-2.181
X2.717Y-4.405
X8.003Y-3.277
X8.009Y-4.448
T2
X2.9854Y-2.235
T3
X3.3134Y-2.865
X5.4866Y-2.235
T0
M30
